// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgrNa2jmHNf6Rc9K1A6fvc9gfe26z-eW4',
    appId: '1:1027991282606:web:b25e23654846f7a9ef9e3f',
    messagingSenderId: '1027991282606',
    projectId: 'newayurveda-a79d7',
    authDomain: 'newayurveda-a79d7.firebaseapp.com',
    storageBucket: 'newayurveda-a79d7.appspot.com',
    measurementId: 'G-SR4MDF38ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgDuZsoURgPPvQSLnAwRjxKdMsH5hfzqU',
    appId: '1:1027991282606:android:80c3eb4caff41e5cef9e3f',
    messagingSenderId: '1027991282606',
    projectId: 'newayurveda-a79d7',
    storageBucket: 'newayurveda-a79d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFshN0Vhq974kscXY9cDlpaL2q4jQ22wM',
    appId: '1:1027991282606:ios:306d1bab43cdefdeef9e3f',
    messagingSenderId: '1027991282606',
    projectId: 'newayurveda-a79d7',
    storageBucket: 'newayurveda-a79d7.appspot.com',
    iosBundleId: 'com.example.ayurVeda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFshN0Vhq974kscXY9cDlpaL2q4jQ22wM',
    appId: '1:1027991282606:ios:90e50d0f0118a972ef9e3f',
    messagingSenderId: '1027991282606',
    projectId: 'newayurveda-a79d7',
    storageBucket: 'newayurveda-a79d7.appspot.com',
    iosBundleId: 'com.example.ayurVeda.RunnerTests',
  );
}
